version: '3.7'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - db:/var/lib/postgresql
        environment:
            - POSTGRES_DB_FILE=/run/secrets/postgres_db
            - POSTGRES_USER_FILE=/run/secrets/postgres_user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
            - postgres_db
            - postgres_password
            - postgres_user
        networks:
            - db

    app:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            - html:/var/www/html
        environment:
            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.fenrir.ovh cloud.alexismartial.fr
            - POSTGRES_HOST=db
            - POSTGRES_DB_FILE=/run/secrets/postgres_db
            - POSTGRES_USER_FILE=/run/secrets/postgres_user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
            - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
            - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
            - REDIS_HOST=redis
            - PHP_UPLOAD_LIMIT=10G
            - NEXTCLOUD_UPDATE=1
        depends_on:
            - db
            - redis
        secrets:
            - nextcloud_admin_password
            - nextcloud_admin_user
            - postgres_db
            - postgres_password
            - postgres_user
        networks:
            - db
            - redis
            - app
        

    web:
        build: ./web
        restart: always
        volumes:
            - html:/var/www/html:ro
        environment:
            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.fenrir.ovh cloud.alexismartial.fr
            - VIRTUAL_HOST=cloud.fenrir.ovh,cloud.alexismartial.fr
            - LETSENCRYPT_HOST=cloud.fenrir.ovh,cloud.alexismartial.fr
            - LETSENCRYPT_EMAIL=contact@alexismartial.fr
        depends_on:
            - app
        networks:
            - nginxproxygitdeploy_net-proxy
            - app

    redis:
        image: redis:alpine
        restart: always
        networks:
            - redis

    cron:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
            - html:/var/www/html
        entrypoint: /cron.sh
        depends_on:
            - db
            - redis
        networks:
            - db
            - redis
    
networks:
    nginxproxygitdeploy_net-proxy:
        external: true
    db:
    redis:
    app:

secrets:
    nextcloud_admin_password:
        file: /secrets/nextcloud_admin_password.txt # put admin password to this file
    nextcloud_admin_user:
        file: /secrets/nextcloud_admin_user.txt # put admin username to this file
    postgres_db:
        file: /secrets/postgres_db.txt # put postgresql db name to this file
    postgres_password:
        file: /secrets/postgres_password.txt # put postgresql password to this file
    postgres_user:
        file: /secrets/postgres_user.txt # put postgresql username to this file

volumes:
    db:
    html:
        driver: local
        driver_opts:
            type: none
            device: "/data/nextcloud/html"
            o: bind
