version: '3.7'

services:
    db:
        image: postgres
        restart: always
        volumes:
            - /data/nextcloud/db:/var/lib/postgresql:rw
        environment:
            - POSTGRES_DB_FILE=/run/secrets/postgres_db
            - POSTGRES_USER_FILE=/run/secrets/postgres_user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
        secrets:
            - postgres_db
            - postgres_password
            - postgres_user
        networks:
            - db

    app:
        image: nextcloud:apache
        restart: always
        volumes:
            - nextcloud:/var/www/html/
            - /data/nextcloud/data:/run/nextcloud/data:rw
        environment:
            - NEXTCLOUD_TRUSTED_DOMAINS=cloud.fenrir.ovh cloud.alexismartial.fr
            - VIRTUAL_HOST=cloud.fenrir.ovh,cloud.alexismartial.fr
            - LETSENCRYPT_HOST=cloud.fenrir.ovh,cloud.alexismartial.fr
            - LETSENCRYPT_EMAIL=contact@alexismartial.fr
            - POSTGRES_HOST=db
            - POSTGRES_DB_FILE=/run/secrets/postgres_db
            - POSTGRES_USER_FILE=/run/secrets/postgres_user
            - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
            - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
            - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
            - REDIS_HOST=redis
            - NEXTCLOUD_DATA_DIR=/run/nextcloud/data
        depends_on:
            - db
            - redis
        secrets:
            - nextcloud_admin_password
            - nextcloud_admin_user
            - postgres_db
            - postgres_password
            - postgres_user
        networks:
            - nginxproxygitdeploy_net-proxy
            - db
            - redis
        

    redis:
        image: redis:alpine
        restart: always
        networks:
            - redis

    cron:
        image: nextcloud:apache
        restart: always
        environment:
            - NEXTCLOUD_DATA_DIR=/run/nextcloud/data
        volumes:
            - nextcloud:/var/www/html
            - /data/nextcloud/data:/run/nextcloud/data:rw
        entrypoint: /cron.sh
        depends_on:
            - db
            - redis
            - app
        networks:
            - db
            - redis
    
networks:
    nginxproxygitdeploy_net-proxy:
        external: true
    db:
    redis:

secrets:
    nextcloud_admin_password:
        file: /secrets/nextcloud_admin_password.txt # put admin password to this file
    nextcloud_admin_user:
        file: /secrets/nextcloud_admin_user.txt # put admin username to this file
    postgres_db:
        file: /secrets/postgres_db.txt # put postgresql db name to this file
    postgres_password:
        file: /secrets/postgres_password.txt # put postgresql password to this file
    postgres_user:
        file: /secrets/postgres_user.txt # put postgresql username to this file

volumes:
    nextcloud:
